// Meta-connectors (always available)
pub mod federated;

#[cfg(feature = "arxiv")]
pub mod arxiv;
#[cfg(feature = "atlassian")]
pub mod atlassian;
#[cfg(feature = "biorxiv")]
pub mod biorxiv;
#[cfg(feature = "discord")]
pub mod discord;
#[cfg(feature = "github")]
pub mod github;
#[cfg(feature = "google-scholar")]
pub mod google_scholar;
#[cfg(feature = "hackernews")]
pub mod hackernews;
#[cfg(feature = "imap")]
pub mod imap;
#[cfg(feature = "macos-automation")]
pub mod macos;
#[cfg(feature = "pubmed")]
pub mod pubmed;
#[cfg(feature = "reddit")]
pub mod reddit;
#[cfg(feature = "rss")]
pub mod rss;
#[cfg(feature = "scihub")]
pub mod scihub;
#[cfg(feature = "semantic-scholar")]
pub mod semantic_scholar;
#[cfg(feature = "slack")]
pub mod slack;
#[cfg(feature = "web")]
pub mod web;
#[cfg(feature = "wikipedia")]
pub mod wikipedia;
#[cfg(feature = "x-twitter")]
pub mod x;
#[cfg(feature = "youtube")]
pub mod youtube;

// LLM provider web search
#[cfg(feature = "anthropic-search")]
pub mod anthropic_search;
#[cfg(feature = "exa-search")]
pub mod exa_search;
#[cfg(feature = "firecrawl-search")]
pub mod firecrawl_search;
#[cfg(feature = "gemini-search")]
pub mod gemini_search;
#[cfg(feature = "openai-search")]
pub mod openai_search;
#[cfg(feature = "perplexity-search")]
pub mod perplexity_search;
#[cfg(feature = "serpapi-search")]
pub mod serpapi_search;
#[cfg(feature = "serper-search")]
pub mod serper_search;
#[cfg(feature = "tavily-search")]
pub mod tavily_search;
#[cfg(feature = "xai-search")]
pub mod xai_search;

// Productivity & Cloud (Phase 1)
#[cfg(feature = "google-calendar")]
pub mod google_calendar;
#[cfg(feature = "google-drive")]
pub mod google_drive;
#[cfg(feature = "google-gmail")]
pub mod google_gmail;
#[cfg(feature = "google-people")]
pub mod google_people;
#[cfg(feature = "microsoft-graph")]
pub mod microsoft;
